[package]
name = "radius-log-browser-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0" # GUI wrapper for egui
egui = "0.26.0"   # Immediate Mode GUI library
egui_extras = { version = "0.26.0", features = ["all_loaders"] } # Table support
quick-xml = { version = "0.31.0", features = ["serialize"] }
rayon = "1.8"
chrono = "0.4"
rfd = "0.12" # Native file dialog
rust_xlsxwriter = "0.63" # Excel Export
anyhow = "1.0"
crossbeam-channel = "0.5" # For async logic/UI communication
serde = { version = "1.0.228", features = ["derive"] }

# Optimize for size
[profile.release]
opt-level = "z"     # Optimize for size (or "s")
lto = true          # Link Time Optimization
codegen-units = 1   # Maximize optimization
panic = "abort"     # Remove unwinding symbols
strip = true        # Strip symbols from binary

[build-dependencies]
winres = "0.1.12"
