[advisories]
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "OFL-1.1",
    "ISC",
    "Zlib",
    "Ubuntu-font-1.0",
    "CDLA-Permissive-2.0",
    "MPL-2.0",
]
[bans]
[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
