[advisories]
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "OFL-1.1",
]
[bans]
[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
