[default.extend-words]
Projet = "Projet"
Construit = "Construit"
sur = "sur"
projet = "projet"
Informe = "Informe"
asInvoker = "asInvoker"
cours = "cours"
Raison = "Raison"

[files]
extend-exclude = ["patches/**/*"]
