[package]
name = "paste-compat"
version = "0.0.0"
authors = ["Aditya Kumar <git@adityais.dev>"]
edition = "2018"
publish = false

[features]
use_original = []

[dependencies]
paste = { version = "1" }
pastey = { path = "../" }
rustversion = "1.0"
